### ISSUE TITLE
American shop redirection

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/shop.o.o#22]
Everytime someone click on the American shop, it redirects to shop.o.o and stays in the Europe store. index-us.html must be redirecting to it. Having the embedded code for both stores US & Europe doesn't appear to work. Ultimately, I settled on index-us.html going to https://openshop.myspreadshop.com/, but I'm not sure that will work either due to <meta http-equiv="refresh" content="0; url='https://shop.opensuse.org/'" /> inside of it.

_Originally posted by @ddemaio in https://github.com/openSUSE/shop.o.o/issues/19#issuecomment-2333934555_

**Comment by ddemaio** [comment]
I guess the code could be more streamlined, but this accomplishes the end result of staying within shop.o.o while moving between the US and Europe shops.
